services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:v3
    container_name: woodpecker-server
    restart: unless-stopped
    ports:
      - "8888:80"
      - "9000:9000"
    volumes:
      - woodpecker-data:/var/lib/woodpecker/
    env_file:
      - .env
    networks:
      - woodpecker

  woodpecker-agent:
    image: woodpeckerci/woodpecker-agent:v3
    container_name: woodpecker-agent
    restart: unless-stopped
    depends_on:
      - woodpecker-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - .env
    networks:
      - woodpecker

volumes:
  woodpecker-data:

networks:
  woodpecker:
    driver: bridge
